Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/test/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
land_110 = regionmask.defined_regions.natural_earth.land_110

land_mask = land_110.mask_3D(tas)

# add a plot
ax = plt.axes(projection=ccrs.Robinson())
land_mask.plot(ax=ax, transform=ccrs.PlateCarree(), add_colorbar=False);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_5633/3765640021.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mland_110[0m [0;34m=[0m [0mregionmask[0m[0;34m.[0m[0mdefined_regions[0m[0;34m.[0m[0mnatural_earth[0m[0;34m.[0m[0mland_110[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mland_mask[0m [0;34m=[0m [0mland_110[0m[0;34m.[0m[0mmask_3D[0m[0;34m([0m[0mtas[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;31m# add a plot[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.7/site-packages/regionmask/defined_regions/_natural_earth.py[0m in [0;36mland_110[0;34m(self)[0m
[1;32m    303[0m             )
[1;32m    304[0m [0;34m[0m[0m
[0;32m--> 305[0;31m             [0mself[0m[0;34m.[0m[0m_land_110[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_obtain_ne[0m[0;34m([0m[0m_land_110[0m[0;34m,[0m [0;34m**[0m[0mopt[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    306[0m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_land_110[0m[0;34m[0m[0;34m[0m[0m
[1;32m    307[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.7/site-packages/regionmask/defined_regions/_natural_earth.py[0m in [0;36m_obtain_ne[0;34m(self, natural_earth_feature, **kwargs)[0m
[1;32m    462[0m             [0mnatural_earth_feature[0m[0;34m.[0m[0mresolution[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    463[0m             [0mnatural_earth_feature[0m[0;34m.[0m[0mcategory[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 464[0;31m             [0mnatural_earth_feature[0m[0;34m.[0m[0mname[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    465[0m         )
[1;32m    466[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/test/lib/python3.7/site-packages/regionmask/defined_regions/_natural_earth.py[0m in [0;36m_get_shapefilename_cartopy[0;34m(resolution, category, name)[0m
[1;32m    518[0m     [0;32mif[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mcartopy_file[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    519[0m         raise ValueError(
[0;32m--> 520[0;31m             [0;34m"``regionmask.defined_regions.natural_earth`` is deprecated. Will not "[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    521[0m             [0;34mf"download new files via this interface. {ALTERNATIVE}."[0m[0;34m[0m[0;34m[0m[0m
[1;32m    522[0m         )

[0;31mValueError[0m: ``regionmask.defined_regions.natural_earth`` is deprecated. Will not download new files via this interface. Please use ``regionmask.defined_regions.natural_earth_v4_1_0`` or ``regionmask.defined_regions.natural_earth_v5_0_0`` instead.
ValueError: ``regionmask.defined_regions.natural_earth`` is deprecated. Will not download new files via this interface. Please use ``regionmask.defined_regions.natural_earth_v4_1_0`` or ``regionmask.defined_regions.natural_earth_v5_0_0`` instead.

